name: Build Workflow

on:
  workflow_dispatch:  # This makes the workflow run only when manually triggered

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.0.app

      - name: Install Dependencies
        run: brew install bash jq meson coreutils pandoc pyenv nvm

      - name: Add to PATH
        shell: bash
        run: |
             echo "$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH

      - name: Grant execute permission to scripts
        run: chmod +x incrementBuildNumber.sh build.sh

      - name: Increment Build Number
        shell: bash
        run: ./incrementBuildNumber.sh

      - name: Run Build Script
        shell: bash
        run: ./build.sh

      - name: Verify Variables
        run: |
          echo "Keyman Engine Tag: $KEYMAN_ENGINE_TAG"
          echo "XC Destination Directory: $XCDEST_DIR"

      - name: Create and push tag
        run: |
          git tag $KEYMAN_ENGINE_TAG
          git push origin --tags

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create -p -d $KEYMAN_ENGINE_TAG --title "KeymanEngine SPM $KEYMAN_ENGINE_TAG" --generate-notes --verify-tag

      - name: Upload binaries to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for f in $(ls "$XCDEST_DIR"); do
            if [[ $f == *.zip ]]; then
              gh release upload $KEYMAN_ENGINE_TAG "$XCDEST_DIR/$f"
            fi
          done

        
