name: Build Workflow

on:
  workflow_dispatch:  # This makes the workflow run only when manually triggered

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.0.app

      - name: Install Dependencies
        run: brew install bash jq meson coreutils pandoc pyenv nvm

      - name: Add to PATH
        shell: bash
        run: |
             echo "$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH

      - name: Grant execute permission to scripts
        run: chmod +x incrementBuildNumber.sh build.sh

      - name: Increment Build Number
        shell: bash
        run: ./incrementBuildNumber.sh

      - name: Run Build Script
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.sh

