name: Build Workflow

on:
  workflow_dispatch:  # This makes the workflow run only when manually triggered

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install bash jq meson coreutils pandoc pyenv

      - name: Grant execute permission to scripts
        run: chmod +x incrementBuildNumber.sh build.sh

      - name: Increment Build Number
        shell: bash
        run: ./incrementBuildNumber.sh

      - name: Run Build Script
        shell: bash
        run: ./build.sh

        
