name: Build Workflow

on:
  workflow_dispatch:  # This makes the workflow run only when manually triggered

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.0.app

      - name: Install Dependencies
        run: brew install bash jq meson coreutils pandoc pyenv nvm

      - name: Add to PATH
        shell: bash
        run: |
             echo "$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH

      - name: Grant execute permission to scripts
        run: chmod +x incrementBuildNumber.sh build.sh

      - name: Set up NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && . "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
          [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && . "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"
          nvm install 18
          nvm use 18
          node -v  # Verify installation

      - name: Increment Build Number
        shell: bash
        run: ./incrementBuildNumber.sh

      - name: Run Build Script
        shell: bash
        run: ./build.sh

        
